name: .NET PR Checks

on:
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore src/BlazorJsManager.sln
      - name: Build
        run: dotnet build src/BlazorJsManager.sln --no-restore --configuration Release
      - name: Test
        run: dotnet test src/BlazorJsManager.sln --no-build --configuration Release --verbosity normal

