# This workflow publishes a NuGet package when a new version tag is pushed
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-packages-to-nuget

name: Publish NuGet

permissions:
  contents: read
  packages: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/BlazorJsManager
      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: src/BlazorJsManager
      - name: Pack
        run: dotnet pack --no-build --configuration Release --output ./nupkg
        working-directory: src/BlazorJsManager
      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        working-directory: src/BlazorJsManager
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.event.head_commit.message }}
          body: ${{ github.event.head_commit.message }}
          target_commitish: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

